from application.entities import BaseScanModelData
from application.entities.upwork.profile import (
    Address, 
    Certificate, 
    Contact, 
    Education, 
    Experiences, 
    Language
)
from typing import List, Optional


class ProfilePageData(BaseScanModelData):
    """Represents partial scan from profile page."""
    full_name: str = ...
    city: str = ...
    country: str = ...
    price_per_hour: str = ...
    profile_description: str = ...
    professional_experiences: List[Experiences] = ...
    languages: List[Language] = ...
    education: List[Education] = ...
    certificates: List[Certificate] = ...
    picture_url: str = ...
    job_title: str = ...


class ContactInfoData(BaseScanModelData):
    """Represents partial scan from contact info page."""
    email: str = ...
    timezone: str = ...
    street: str = ...
    street_complement: str = ...
    zipcode: str = ...
    phone_number: str = ...
    country_code: str = ...


class MainPageData(BaseScanModelData):
    """Represents partial scan from upwork main page platform."""
    username: str = ...
    profile_visibility: str = ...
    available_hours: str = ...
    profile_completion: str = ...
    proposals: str = ...
    categories: List[str] = ...


class FullScanProfile(BaseScanModelData):
    """Represents full scan from upwork platform."""
    uuid: str = ...
    full_name: str = ...
    address: Address = ...
    contact: Contact = ...
    country_code: str = ...
    profile_description: str = ...
    professional_experiences: List[Experiences] = ...
    languages: List[Language] = ...
    education: List[Education] = ...
    certificates: List[Certificate] = ...
    created_at: str = ...
    updated_at: Optional[str]
    picture_url: str = ...
    job_title: str = ...
